# Generated by Django 4.0.4 on 2022-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modretur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id1', models.PositiveIntegerField()),
                ('birthday', models.DateField()),
                ('gpa', models.FloatField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('level', models.CharField(choices=[('F', 'First level'), ('S', 'Second level'), ('T', 'Third level'), ('O', 'Fourth level')], max_length=20)),
                ('depart', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('DS', 'DS'), ('AI', 'AI'), ('IS', 'IS')], max_length=20)),
                ('status', models.CharField(choices=[('Ac', 'Active'), ('In', 'Inactive')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
