# Generated by Django 4.0.4 on 2022-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_remove_students_id_alter_students_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modretur',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='level',
            field=models.CharField(choices=[('First level', 'First level'), ('Second level', 'Second level'), ('Third level', 'Third level'), ('Fourth level', 'Fourth level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
